name: TEST

on:
  push:
    branches: [ master ]


  workflow_dispatch:

jobs:
  job_one:
    name: tests
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: 54.198.167.77
          username: ubuntu
          key: ${{ secrets.TEST_SSH }}
          port: 22
          script: |
            echo "connection worked"
